# Generated by Django 5.0.6 on 2024-07-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_author', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Цитата',
                'verbose_name_plural': 'Цитаты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.language')),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quote.quote')),
            ],
            options={
                'verbose_name': 'Перевод цитаты',
                'verbose_name_plural': 'Переводы цитат',
                'ordering': ['id'],
                'unique_together': {('quote_id', 'lang')},
            },
        ),
    ]
